#+OPTIONS: toc:nil num:nil
#+LANGUAGE: es
#+BEGIN_EXPORT html
---
layout: post
title: "Sueño submarino"
date: 2021-05-24 12:18:34
tags: ["ficción"]
---
#+END_EXPORT

Volvemos de algún campamento o viaje de egresados con los compañeros del colegio; es el viaje de vuelta, ya estamos cerca de casa, pero en vez de micro vamos en una especie de submarino gigante. Estamos un recinto con paredes y columnas metálicas, la habitación es tan grande que se parece más bien a esos hangares espaciales por donde ingresan las naves en /Star Wars/. Cambia el punto de vista hacia el exterior del submarino; no se lo ve en el agua sino flotando en el aire, a escasa altura sobre la avenida Costanera, esquivando árboles y postes de luz. La imagen lo muestra como una nave que flota pero es un submarino y está bajo el agua, es algo que no se ve pero se sabe y /se siente/ en el interior, en el hangar donde desayuno con mis compañeros.

Estamos sentados en unas mesas de tablones alargados, como de quincho. Al lado mío están Maciel, Neri, Ota; terminamos de desayunar, hablamos de cosas sin importancia, nos tiramos pedazos de pan con la mesa de enfrente. En un extremo del hangar hay un portón corredizo y más allá otro recinto, como un hall, de cuyo centro se elevan dos escaleras que llevan a la superficie. Todas las otras paredes del hangar están pobladas de aberturas que comunican con las celdas o cabinas en las que dormimos; al pensar en ellas cambia el punto de vista y veo mi propia celda, cuatro camas empotradas en la pared metálica, la mochila vacía, mis pertenencias desparramadas sobre la cama y el suelo; recorro las cosas con la vista, me extraño y me inquieto porque a mi me gusta armar el equipaje con tiempo, casi siempre lo hago la noche anterior sin importar la hora de partida y este caso se sabe que estamos cerca de llegar, acaso el submarino vaya a estacionar en la terminal de ómnibus de retiro.

Nos levantamos, chocamos con los de la mesa de enfrente, Pancho me roba el bolso de mano, se pone a buscar en los bolsillos pero lo único que hay es un pañuelo. A falta de otra cosa, se suena los mocos, vuelve a poner el pañuelo adentro del bolso y quiere devolvérmelo. Le digo que no, que ahora tiene sus gérmenes, que es peligroso que yo saque a pasear los gérmenes de otra persona. Los demás están de acuerdo. Le digo que se lleve la mochila, que la lave en su casa y me la devuelva; Pancho putea resignado.

Cambia la perspectiva, otra vez se ve al submarino maniobrando trabajosamente en el aire, demasiado bajo y demasiado lento, no hace a tiempo a girar y se choca de frente con lo que parecería ser un quiosco de revistas pero es más probablemente un puesto de choripanes. Uno se esperaría que semejante nave haría volar en mil pedazos el puestito pero en cambio es el submarino el que se lleva lo peor; de vuelta en el hangar se apagaron las luces y suena una alarma; no vemos pero /sabemos/ que el submarino se llena de agua, sabemos que se hunde aunque la imagen lo mostraba volando y aunque ya estuviera sumergido, se hunde como un micro que se desbarranca y cae al mar, el hangar se llena de agua, el techo se viene abajo como si fuera el fondo de una piscina.

Yo tengo el impulso a salir nadando hacia la superficie antes de alcanzar una profundidad insalvable pero la siguiente imagen desmiente un poco lo anterior, el submarino vuelve a ser un submarino, uno que se inunda, sí, pero al menos no se hunde, el agua se filtra y nos moja los talones pero todavía hay un techo. La situación es relativamente menos apremiante pero persiste el impulso de escapar nadando, solo que para eso primero habría que salir del submarino, subir por la escalera en la sala contigua. Intento moverme en esa dirección pero las piernas me fallan, es como si estuvieran adheridas por el agua que ya me llega a los tobillos.

En eso entra al recinto la coordinadora del campamento, una mujer con aire de profesora de ciencias, y nos pide que mantengamos la calma. Se sienta en una de las mesas alargadas y saca un manual de operaciones, un libraco que evoca plantas nucleares soviéticas, busca  el procedimiento para emergencias. Se toma su tiempo, se moja el dedo y pasa las páginas con parsimonia, como si no corriera el agua por las paredes y las espaldas.

Yo sigo desesperado por salir pero me someto a la autoridad de la Profesora, admito que mi impulso anterior consideraba únicamente mi propia supervivencia mientras que la Profesora se hace responsable por el grupo. Después de otro rato de gestos concentrados y resoplidos de fastidio, sin embargo, llega a la conclusión de que no hay manera de salvar la nave y que hay que evacuar ordenadamente. Nos manda a todos a nuestras cabinas a buscar provisiones y a reunirnos en diez minutos alrededor de la escalera de salida. Nos pide específicamente que perdamos el tiempo tratando de rescatar el equipaje, que ella se compromete a mandarlo a buscar más adelante. No sé exactamente qué se propone la Profesora pero evidentemente anticipa algún tipo de expedición de supervivencia porque su última indicación es la de reunir todos los alimentos que encontremos, como si nos dispusiéramos a esperar el rescate en una isla desierta. Me apuro hacia mi cabina y pienso para mis adentros que es /exactamente/ este tipo de catástrofe la razón por la que uno se toma el tiempo de preparar el equipaje con antelación y que, aunque sobreviva, nunca me voy a perdonar que mis pertenencias hayan quedado desparramadas por el piso del submarino.

Cargo el bolso de mano con los dos alfajores y la botella de agua mineral que me quedan y vuelvo hacia el hall de entrada, donde el resto del grupo se coloca en fila india para salir por la escalera. No queda del todo claro cómo podríamos abrir la escotilla siendo que es de arriba de donde llega el agua, que a esta altura ya nos toca los hombros. Y no tengo tiempo de averiguarlo porque ahí es cuando me despierto.
